site_name: "Mon Portfolio"



nav:
  - Accueil:
      - A propos de moi: index.md
      - Sommaire: Somaires.md
  - RÃ©fÃ©rentiel des CompÃ©tences: referenciel.md
  - ğŸ“š Projet :
      - ğŸ“Œ Semestre 1:
          - ğŸ’§ Station de pompage:
              - Concevoir: concevoir_station_pompage.md
              - VÃ©rifier: verifier_station_pompage.md
          - ğŸ¤– Robot Suiveur de Ligne:
              - Concevoir: concevoir_robot_suiveur.md
              - VÃ©rifier: verifier_robot_suiveur.md
      - ğŸ… Semestre 2:
          - ğŸ“– Moteur de drone:
              - Concevoir: concevoir_moteur_drone.md
              - VÃ©rifier: verifier_moteur_drone.md
          - ğŸ¨ Snake:
              - Concevoir: concevoir_sae_snake.md
              - VÃ©rifier: verifier_sae_snake.md
  - Mon experience personnel: 
      - ğŸ“‚ Projets et CompÃ©tences:
          - ğŸ† Projets en paralle: projet_realiser.md
          - ğŸ”§ CompÃ©tences: competence_aquise.md
                      
  - ğŸ“ Contact: contact.md


site_name: "Mon Portfolio"
theme:
  name: "material"
  palette:
    scheme: white  # Fond sombre stylÃ© / "default" pour fond clair
    primary: indigo
    accent: pink
  font:
    text: Roboto
    code: Roboto Mono
  logo: "images/Logo-IUT-UM-Horizontal-couleur.png"
  favicon: "images/favicon.ico"
  features:
    - navigation.instant  # Chargement rapide des pages
    - navigation.tracking  # Garde la position dans la navigation
    - navigation.sections  # Regroupe les menus
    - navigation.expand  # Ouvre automatiquement le menu latÃ©ral
    - navigation.tabs  # Affiche un menu sous forme d'onglets (optionnel)
    - navigation.top  # Bouton retour en haut de la page
    - toc.integrate  # IntÃ¨gre la table des matiÃ¨res dans le menu latÃ©ral
    

extra_css:
  - css/extra.css
  
  
extra_javascript:
  - https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700&display=swap